kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
- name: jira
  image: rickcraigharness/drone-jira
  settings:
    url: https://harness.atlassian.net/
    username: richard.craig@harness.io
    token: Kyjl8auYQX0G1eH0IbA33239

