kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm test
- name: jira
  image: rickcraigharness/drone-jira
  settings:
    url: https://rick-dev.atlassian.net/
    username: richard.craig@gmail.com
    token: qt4t5I9sI3l0Ho56PMyMAB7C

